### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by CompileNix** [jasonba/zfs_arc_shrink_shift#1]
> $ make zfs_arc_shrink_shift
> cc  -o zfs_arc_shrink_shift zfs_arc_shrink_shift.c
> /tmp/ccqYIHn8.o: In function `main':
> zfs_arc_shrink_shift.c:(.text+0x127): undefined reference to `log2'
> zfs_arc_shrink_shift.c:(.text+0x12c): undefined reference to `round'
> zfs_arc_shrink_shift.c:(.text+0x183): undefined reference to `log2'
> zfs_arc_shrink_shift.c:(.text+0x188): undefined reference to `round'
> collect2: error: ld returned 1 exit status
> Makefile:22: recipe for target 'zfs_arc_shrink_shift' failed
> make: *** [zfs_arc_shrink_shift] Error 1

Am i missing any dependency?
Do you need any additional information, if so which?

**Comment by jasonba** [comment]
Hi there,

You didn't mention which platform you're trying to compile this on.
On MacOS 10.12 (Sierra) it compiles without problems.
On Linux you'll need to compile and link in the maths library, eg:

$ cc -o zfs_arc_shrink_shift zfs_arc_shrink_shift.c -lm

For a NexentaStor or Illumos distribution, I can compile it again using -lm but I have to make some changes:

1) u_int64_t becomes uint64_t
2) I need to include <stdint.h>

When I wrote this it was originally just for testing on my Mac but clearly I need to make this more platform agnostic.

Let me know if you get it to compile.

- JB

**Comment by jasonba** [comment]
Hi again,

I've reworked the code to make it more platform agnostic and have tested compiling it on a Mac, on a Linux box and also on a NexentaStor appliance.
As you can see you just need to use the appropriate Makefile for one of these platforms and it should now compile ok.

Feel free to pull the new code and give it a go.

- JB

**Comment by CompileNix** [comment]
Nice, i'll try it out later this day.
I'm using Gentoo Linux.

**Comment by CompileNix** [comment]
That's it, it builds and works just fine now.

I build it using:
```bash
rm Makefile
ln -s Makefile.Linux Makefile
make zfs_arc_shrink_shift
```

many thanks!
